name: markboot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.5+4135

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  lottie: ^1.0.1
  timer_button: ^1.0.2
  bot_toast: ^4.0.1
  cloud_firestore: ^2.2.0
  firebase_messaging: ^10.0.0
  loading_animations: ^2.2.0
  http: ^0.13.3
  flutter_local_notifications: 
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  flutter_swiper: ^1.1.6
  flutter_downloader: ^1.4.4
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  fluttertoast: ^8.0.7
  pinput: ^1.2.0
  firebase_storage: ^8.1.1
  path_provider: ^2.0.2
  permission_handler: ^8.0.1
  image_picker: ^0.8.0+1
  pull_to_refresh: ^2.0.0
  file_picker: ^3.0.2+2
  flutter_mailer: ^2.0.0
  url_launcher: ^6.0.6
  share: ^2.0.4
  google_fonts: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/home.png
    - assets/icons/hunt.png
    - assets/icons/offers.png
    - assets/icons/gigs.png
    - assets/icons/person.png
    - assets/icons/intern.png
    - assets/icons/tourn.png
    - assets/icons/career.png
    - assets/icons/user.png
    - assets/icons/menu.png
    - assets/icons/aboutus.png
    - assets/icons/contactus.png
    - assets/icons/logout.png
    - assets/icons/privacy.png
    - assets/icons/share.png
    - assets/icons/issue.png
    - assets/icons/camera.png
    - assets/icons/list.png
    - assets/icons/money.png
    - assets/icons/purchase.png
    - assets/icons/internship.png
    - assets/icons/bank.png
    - assets/icons/mb_icon.png
    - assets/icons/mb_icon-r.png
    - assets/Json/splash.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
